name: Parser

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'  # 10:00 Moscow time (UTC+3)

jobs:
  run-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install dependencies
        run: npm install
      - name: Run parser
        id: run-parser
        run: |
          node index.js 2>&1 | tee error.log
          echo "ERROR_LOG<<EOF" >> $GITHUB_ENV
          cat error.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Check if parser failed
        if: failure()
        run: |
          echo "Parser failed, will retry in 15 minutes"
          echo "RETRY=true" >> $GITHUB_ENV
      - name: Wait 15 minutes
        if: failure()
        run: sleep 900
      - name: Retry parser
        if: failure()
        run: |
          node index.js 2>&1 | tee error.log
          echo "ERROR_LOG<<EOF" >> $GITHUB_ENV
          cat error.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Parser Failed
          body: |
            Parser failed after retry. Please check the logs.
            
            Error log:
            ```
            ${{ env.ERROR_LOG }}
            ```
          to: ${{ secrets.EMAIL_USER }}
          from: GitHub Actions
      - name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Parser Success
          body: |
            Parser completed successfully!
            
            Log:
            ```
            ${{ env.ERROR_LOG }}
            ```
          to: ${{ secrets.EMAIL_USER }}
          from: GitHub Actions 