name: Parser

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'

jobs:
  parse:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Setup Chromedriver (pin to Chrome 140)
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '140.0.7339.0'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Remove npm chromedriver from PATH
      run: |
        rm -f node_modules/.bin/chromedriver || true
        rm -f node_modules/.bin/chromedriver.exe || true
        rm -f node_modules/.bin/chromedriver.cmd || true

    - name: Verify Chrome and Chromedriver versions
      run: |
        google-chrome --version || true
        chromedriver --version || true

    - name: Export CHROMEDRIVER_PATH for app
      run: echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV

    - name: Run parser
      env:
        USE_NPM_CHROMEDRIVER: '0'
      run: node index.js
      
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Parser Results
        body: |
          Results from Parser:
          
          Please find the attached files with the results.
        from: ${{ secrets.EMAIL_USER }}
        to: ${{ secrets.EMAIL_USER }}
        secure: true
        attachments: results/*.json,results/*.csv 